# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=45, verbose_name='姓名')),
                ('student_num', models.CharField(max_length=45, unique=True, verbose_name='学号')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='static/student', verbose_name='头像')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='班级')),
            ],
            options={
                'verbose_name_plural': '学生信息',
                'verbose_name': '学生信息',
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=45, verbose_name='姓名')),
                ('teacher_num', models.CharField(max_length=45, verbose_name='职工号')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/teacher', verbose_name='头像')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='系')),
            ],
            options={
                'verbose_name_plural': '教师信息',
                'verbose_name': '教师信息',
                'db_table': 'teacher_info',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('categroy', models.CharField(choices=[('学生', '学生'), ('教师', '教师')], default='学生', max_length=12, verbose_name='权限')),
                ('name', models.CharField(max_length=45, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '登录信息',
                'verbose_name': '登录信息',
                'db_table': 'users_info',
            },
        ),
    ]
