# Generated by Django 2.0.4 on 2018-05-17 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('users', '0002_auto_20180517_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='所属教学单位'),
            preserve_default=False,
        ),
    ]
