# Generated by Django 2.0.4 on 2018-05-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='所在系'),
        ),
    ]
