# Generated by Django 2.0.4 on 2018-04-24 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=45, verbose_name='年级')),
                ('major', models.CharField(max_length=45, verbose_name='专业')),
                ('classes', models.IntegerField(default=1, unique=True, verbose_name='班号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
                'db_table': 'classroom_info',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='系名')),
                ('number', models.IntegerField(unique=True, verbose_name='系编号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '系别信息',
                'verbose_name_plural': '系别信息',
                'db_table': 'department_info',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=45, verbose_name='姓名')),
                ('student_num', models.CharField(max_length=45, unique=True, verbose_name='学号')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='static/student', verbose_name='头像')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=45, verbose_name='姓名')),
                ('teacher_num', models.CharField(max_length=45, verbose_name='职工号')),
                ('teacher_rank', models.CharField(max_length=45, verbose_name='职称')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/teacher', verbose_name='头像')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='系')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teacher_info',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='系名'),
        ),
    ]
