# Generated by Django 2.0.2 on 2018-04-16 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=45, verbose_name='年级')),
                ('major', models.CharField(max_length=45, verbose_name='专业')),
                ('classes', models.IntegerField(default=1, unique=True, verbose_name='班号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '班级信息',
                'verbose_name': '班级信息',
                'db_table': 'classroom_info',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='系名')),
                ('number', models.IntegerField(unique=True, verbose_name='系编号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '系别信息',
                'verbose_name': '系别信息',
                'db_table': 'department_info',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='系名'),
        ),
    ]
