# Generated by Django 2.0.2 on 2018-05-08 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名称')),
                ('desc', models.TextField(verbose_name='班级描述')),
                ('grade', models.CharField(choices=[('freshman', '大一'), ('sophomore', '大二'), ('junior', '大三'), ('senior', '大四')], default='freshman', max_length=45, verbose_name='年级')),
                ('major', models.CharField(max_length=45, verbose_name='专业')),
                ('classes', models.IntegerField(default=1, verbose_name='班号')),
                ('students', models.IntegerField(default=0, verbose_name='班级人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '班级信息',
                'verbose_name_plural': '班级信息',
                'db_table': 'classroom_info',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='教学单位')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '教学单位',
                'verbose_name_plural': '教学单位',
                'db_table': 'department_info',
            },
        ),
    ]
