# Generated by Django 2.0.2 on 2018-05-08 13:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=45, verbose_name='姓名')),
                ('number', models.CharField(max_length=45, unique=True, verbose_name='学号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student_info',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=45, verbose_name='姓名')),
                ('number', models.CharField(max_length=45, verbose_name='职工号')),
                ('work_years', models.CharField(max_length=45, verbose_name='教学年限')),
                ('rank', models.CharField(max_length=45, verbose_name='职称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '教师信息',
                'verbose_name_plural': '教师信息',
                'db_table': 'teacher_info',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='所在教学单位'),
        ),
    ]
