# Generated by Django 2.0.4 on 2018-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='department/%Y/%m', verbose_name='教学单位图片'),
        ),
    ]
