# Generated by Django 2.0.4 on 2018-05-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='classroom/%Y/%m', verbose_name='班级图片'),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='department/%Y/%m', verbose_name='教学单位图片'),
        ),
    ]
