# Generated by Django 2.0.4 on 2018-05-22 23:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='标题')),
                ('g_content', models.TextField(verbose_name='内容')),
                ('g_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='留言时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='留言者')),
            ],
            options={
                'verbose_name': '留言管理',
                'verbose_name_plural': '留言管理',
                'db_table': 'guestbook_info',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_content', models.TextField(verbose_name='回复内容')),
                ('r_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('guestbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestbook.GuestBook', verbose_name='留言')),
                ('next_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestbook.Reply', verbose_name='回复')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'verbose_name': '留言回复管理',
                'verbose_name_plural': '留言回复管理',
                'db_table': 'reply_info',
            },
        ),
    ]
