# Generated by Django 2.0.2 on 2018-05-22 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guestbook', '0003_auto_20180521_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_content', models.TextField(verbose_name='回复内容')),
                ('r_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'verbose_name_plural': '留言回复管理',
                'db_table': 'reply_info',
                'verbose_name': '留言回复管理',
            },
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='r_content',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='r_time',
        ),
        migrations.RemoveField(
            model_name='guestbook',
            name='type',
        ),
        migrations.AddField(
            model_name='guestbook',
            name='reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guestbook.Reply', verbose_name='回复'),
            preserve_default=False,
        ),
    ]
