# Generated by Django 2.0.2 on 2018-05-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_auto_20180522_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbook',
            name='reply',
        ),
        migrations.AddField(
            model_name='reply',
            name='guestbook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guestbook.GuestBook', verbose_name='留言'),
            preserve_default=False,
        ),
    ]
