# Generated by Django 2.0.2 on 2018-05-11 14:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_manager', '0001_initial'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='题目')),
                ('introduction', models.CharField(max_length=100, verbose_name='简介')),
                ('content', models.TextField(verbose_name='内容')),
                ('picture', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='news/%Y/%m', verbose_name='图片')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'db_table': 'news_info',
                'verbose_name_plural': '新闻管理',
                'verbose_name': '新闻管理',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='题目')),
                ('introduction', models.CharField(max_length=100, verbose_name='简介')),
                ('content', models.TextField(verbose_name='内容')),
                ('picture', models.ImageField(blank=True, default='image/default.png', null=True, upload_to='notice/%Y/%m', verbose_name='图片')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'db_table': 'notice_info',
                'verbose_name_plural': '公告管理',
                'verbose_name': '公告管理',
            },
        ),
        migrations.CreateModel(
            name='UserAsk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '用户学习',
                'verbose_name': '用户学习',
            },
        ),
        migrations.CreateModel(
            name='WorkCommit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('freshman', '大一'), ('sophomore', '大二'), ('junior', '大三'), ('senior', '大四')], default='freshman', max_length=45, verbose_name='年级')),
                ('title', models.CharField(max_length=45, verbose_name='作业题目')),
                ('content', models.FileField(upload_to='work/content/%Y/%m', verbose_name='作业内容')),
                ('image', models.ImageField(default='image/default.png', upload_to='work/%Y/%m', verbose_name='图片')),
                ('commit_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='提交时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='班级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Course', verbose_name='课程名')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Student', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Teacher', verbose_name='教师')),
            ],
            options={
                'db_table': 'work_commit',
                'verbose_name_plural': '学生作业管理',
                'verbose_name': '学生作业管理',
            },
        ),
        migrations.CreateModel(
            name='WorkPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='作业题目')),
                ('publish_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Course', verbose_name='课程名')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Teacher', verbose_name='教师')),
            ],
            options={
                'db_table': 'work_publish',
                'verbose_name_plural': '作业发布管理',
                'verbose_name': '作业发布管理',
            },
        ),
    ]
