# Generated by Django 2.0.2 on 2018-04-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platfrom', '0001_initial'),
        ('course_manager', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='work',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Teacher', verbose_name='教师'),
        ),
    ]
