# Generated by Django 2.0.2 on 2018-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platfrom', '0001_initial'),
        ('course_manager', '0002_course_course_teacher'),
        ('college', '0002_auto_20180508_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpublish',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Teacher', verbose_name='教师'),
        ),
        migrations.AddField(
            model_name='workcommit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Course', verbose_name='课程名'),
        ),
        migrations.AddField(
            model_name='workcommit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Student', verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='workcommit',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Teacher', verbose_name='教师'),
        ),
    ]
