# Generated by Django 2.0.2 on 2018-05-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platfrom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AlterField(
            model_name='news',
            name='introduction',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='introduction',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
    ]
