# Generated by Django 2.0.2 on 2018-05-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platfrom', '0002_auto_20180504_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=1, verbose_name='内容'),
            preserve_default=False,
        ),
    ]
