# Generated by Django 2.0.2 on 2018-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platfrom', '0002_auto_20180508_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcommit',
            name='grade',
            field=models.CharField(choices=[('freshman', '大一'), ('sophomore', '大二'), ('junior', '大三'), ('senior', '大四')], default='freshman', max_length=45, verbose_name='年级'),
        ),
    ]
