# Generated by Django 2.0.2 on 2018-05-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platfrom', '0004_workcommit_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcommit',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='work/%Y/%m', verbose_name='图片'),
        ),
    ]
