# Generated by Django 2.0.2 on 2018-05-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platfrom', '0005_workcommit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcommit',
            name='content',
            field=models.FileField(upload_to='work/content/%Y/%m', verbose_name='作业内容'),
        ),
    ]
