# Generated by Django 2.0.2 on 2018-04-16 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=45, verbose_name='课程名')),
                ('course_num', models.IntegerField(unique=True, verbose_name='课程号')),
                ('course_intro', models.TextField(blank=True, null=True, verbose_name='课程介绍')),
                ('course_picture', models.ImageField(blank=True, default='static/image/default.png', null=True, upload_to='static/course/image', verbose_name='课程图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '课程信息',
                'verbose_name': '课程信息',
                'db_table': 'course_info',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=100, verbose_name='资料名称')),
                ('data', models.FileField(upload_to='static/course/data', verbose_name='课程资料')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '课程资料',
                'verbose_name': '课程资料',
                'db_table': 'course_data',
            },
        ),
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_name', models.CharField(max_length=100, verbose_name='课件名称')),
                ('ppt', models.FileField(upload_to='static/course/ppt', verbose_name='课件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '课件',
                'verbose_name': '课件',
                'db_table': 'course_ppt',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=45, verbose_name='姓名')),
                ('teacher_num', models.CharField(max_length=45, verbose_name='职工号')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='女', max_length=6, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/teacher', verbose_name='头像')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Department', verbose_name='系')),
            ],
            options={
                'verbose_name_plural': '教师信息',
                'verbose_name': '教师信息',
                'db_table': 'teacher_info',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=100, verbose_name='视频名')),
                ('url', models.URLField(max_length=150, verbose_name='视频地址')),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长（分钟数)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_manager.Course', verbose_name='课程名')),
            ],
            options={
                'verbose_name_plural': '课程视频',
                'verbose_name': '课程视频',
                'db_table': 'course_video',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ManyToManyField(to='course_manager.Teacher', verbose_name='课程教师'),
        ),
    ]
