# Generated by Django 2.0.2 on 2018-05-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_manager', '0001_initial'),
        ('college', '0002_auto_20180508_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.Teacher', verbose_name='课程教师'),
        ),
    ]
