# Generated by Django 2.0.2 on 2018-05-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0002_course_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_teacher',
        ),
    ]
