# Generated by Django 2.0.2 on 2018-05-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_remove_classroom_course'),
        ('course_manager', '0003_remove_course_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='所属班级'),
            preserve_default=False,
        ),
    ]
