# Generated by Django 2.0.4 on 2018-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0005_course_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='classroom/%Y/%m', verbose_name='班级图片'),
        ),
    ]
