# Generated by Django 2.0.4 on 2018-05-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20180511_0005'),
        ('course_manager', '0006_auto_20180511_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.Classroom', verbose_name='所属班级'),
            preserve_default=False,
        ),
    ]
